name: Example kube pipeline
on:
    push:
        branches: master
jobs:
    docker-build:
        runs-on: ubuntu-latest
        steps:
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v1
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1
        -
            name: Login to DockerHub
            uses: docker/login-action@v1
            with:
                username: tomcooperca
                password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
            name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
                push: true
                tags: tomcooperca/example-nginx:${{ github.sha }}
        -
            name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }}
        -
            uses: imranismail/setup-kustomize@v1
            with:
                kustomize-version: "3.1.0"
        -   
            name: Set image tag
            working-directory: ./overlays/dev
            run: kustomize edit set image tomcooperca/example-nginx:$GITHUB_SHA
        - uses: engineerd/setup-kind@v0.3.0
        -
            name: Install to dev
            working-directory: ./overlays/dev
            run: |
                kubectl cluster-info
                kustomize build . | kubectl apply -f -
